""""
Nombre: Juan Pablo Quijano Martinez
Fecha: 11/08/2025Descripcion: 
Este programa permite a una empresa calcular la huella de carbono de cada sede"""



import os

iniciar = bool(input('¿desea calcular el valor de la huella de carbono? si(s) o no(enter :)'))
while True:
    os.system ('clear')
    cual = int(input('\n 1)Oficina 1\n 2)oficina 2 \n 3)oficina 3 \n 4)oficina 4 \n 5)oficica 5 \n 6)TOTAL de todas las oficinas \n :'))
    match cual:
        case 1:

            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 1 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 1 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 1 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 1 :'))
            oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 1 :'))
            oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 1 :'))
            oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 1 :'))
            oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 1 :')) 
            oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
            oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            factor_emision = 0.5
            emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
            emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
            emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
            emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
            emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
            emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
            emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
            emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
            promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
            promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
            promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
            promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
            promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
            promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
            promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
            promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
            consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
            consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
            consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
            consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
            consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
            emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
            emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
            emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
            emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
            emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
            emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
            emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
            emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
            emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 + emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1


            print (f'la ofinina 1 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
            x = input ('presione tecla para continuar......')
    
        case 2:
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 2 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 2 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 2 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 2 :'))
            oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 2 :'))
            oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 2 :'))
            oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 2 :'))
            oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 2 :')) 
            oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
            oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            factor_emision = 0.5
            emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
            emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
            emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
            emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
            emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
            emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
            emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
            emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
            promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
            promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
            promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
            promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
            promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
            promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
            promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
            promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
            consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
            consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
            consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
            consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
            consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
            emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
            emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
            emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
            emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
            emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
            emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
            emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
            emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
            emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 +    emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1
            print (f'la ofinina 2 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
            x = input ('presione tecla para continuar......')
        case 3:
             oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 2 :'))
             oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 2 :'))
             oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 2 :'))
             oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 2 :'))
             oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 2 :'))
             oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 2 :'))
             oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 2 :'))
             oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 2 :')) 
             oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
             oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
             factor_emision = 0.5
             emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
             emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
             emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
             emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
             emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
             emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
             emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
             emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
             promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
             promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
             promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
             promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
             promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
             promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
             promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
             promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
             consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
             consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
             consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
             consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
             consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
             consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
             consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
             consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
             emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
             emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
             emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
             emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
             emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
             emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
             emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
             emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
             emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 +    emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1
             print (f'la ofinina 3 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
             x = input ('presione tecla para continuar......')
        case 4 :
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 2 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 2 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 2 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 2 :'))
            oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 2 :'))
            oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 2 :'))
            oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 2 :'))
            oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 2 :')) 
            oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
            oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            factor_emision = 0.5
            emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
            emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
            emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
            emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
            emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
            emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
            emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
            emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
            promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
            promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
            promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
            promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
            promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
            promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
            promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
            promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
            consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
            consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
            consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
            consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
            consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
            emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
            emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
            emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
            emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
            emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
            emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
            emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
            emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
            emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 +    emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1
            print (f'la ofinina 4 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
            x = input ('presione tecla para continuar......')
        case 5:
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 2 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 2 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 2 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 2 :'))
            oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 2 :'))
            oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 2 :'))
            oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 2 :'))
            oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 2 :')) 
            oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
            oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            factor_emision = 0.5
            emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
            emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
            emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
            emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
            emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
            emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
            emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
            emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
            promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
            promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
            promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
            promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
            promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
            promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
            promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
            promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
            consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
            consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
            consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
            consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
            consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
            emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
            emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
            emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
            emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
            emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
            emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
            emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
            emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
            emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 +    emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1
            print (f'la ofinina 5 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
            x = input ('presione tecla para continuar......')
        case 6:
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 1 :'))
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 2 :'))
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 3 :'))
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 4 :'))
            oficina1_computadores = int(input('ingrese el numero de computadores de la oficina 5 :'))

            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 1 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 2 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 3 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 4 :'))
            oficina1_monitores = int(input('ingrese el numero de monitores que hay en la oficina 5 :'))

            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 1 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 2 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 3 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 4 :'))
            oficina1_impresora = int(input('ingrese el numero de impresoras que hay en la oficina 5 :'))

            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 1 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 2 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 3 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 4 :'))
            oficina1_ventiladores = int(input('ingrese el numero de ventiladores que hay en la oficina 5 :'))
            oficina1_airesacondicionados = int(input('ingrese el numero de aires acondicionados que hay en la oficina 2 :'))
            oficina1_refrigeradores = int(input('ingrese el numero de refrigeradores que hay en la oficina 2 :'))
            oficina1_iluminacion = int(input('ingrese el numero de iluminadores que hay en la oficina 2 :'))
            oficina1_otros = int(input('ingrese el numero de equipos adicionales a los anteriormente mencionados que hay en la oficina 2 :')) 
            oficina1_computadores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los computadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_monitores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los monitores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_impresora_consumoenergetico = float(input('Ingrese el consumo energetico de una de las impresoras (puede estar indicado en la etiqueta energetica o en el manual de usuario) :)'))
            oficina1_ventiladores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los ventiladores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_airesacondicionados_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los aires acondicionados (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_refrigeradores_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los refrigeradores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_iluminacion_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los iluminadores (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            oficina1_otros_consumoenergetico = float(input('Ingrese el consumo energetico de uno de los dispositivos adicionales (puede estar indicado en la etiqueta energetica o en el manual de usuario) :'))
            factor_emision = 0.5
            emision_computador_oficina1 = oficina1_computadores_consumoenergetico * factor_emision
            emision_monitores_oficina1 = oficina1_monitores_consumoenergetico * factor_emision
            emision_impresora_oficina1 = oficina1_impresora_consumoenergetico * factor_emision
            emision_ventiladores_oficina1 = oficina1_ventiladores_consumoenergetico * factor_emision
            emision_airesacondicionados_oficina1 = oficina1_airesacondicionados_consumoenergetico * factor_emision
            emision_refrigeradores_oficina1 = oficina1_refrigeradores_consumoenergetico * factor_emision
            emision_iluminacion_oficina1 = oficina1_iluminacion_consumoenergetico * factor_emision
            emision_otros_oficina1 = oficina1_otros_consumoenergetico * factor_emision
            promedio_consumo_computadoreso1 = (oficina1_computadores * oficina1_computadores_consumoenergetico) / oficina1_computadores_consumoenergetico
            promedio_consumo_monitoreso1 = (oficina1_monitores * oficina1_monitores_consumoenergetico) / oficina1_monitores
            promedio_consumo_impresorao1 = (oficina1_impresora * oficina1_impresora_consumoenergetico) / oficina1_impresora
            promedio_consumo_ventiladores1 = (oficina1_ventiladores * oficina1_ventiladores_consumoenergetico) / oficina1_ventiladores
            promedio_consumo_airesacondicionadoso1 = (oficina1_airesacondicionados * oficina1_airesacondicionados_consumoenergetico) / oficina1_airesacondicionados
            promedio_consumo_refrigeradoreso1 = (oficina1_refrigeradores * oficina1_refrigeradores_consumoenergetico) / oficina1_refrigeradores
            promedio_consumo_iluminaciono1 = (oficina1_iluminacion * oficina1_iluminacion_consumoenergetico) / oficina1_iluminacion
            promedio_consumo_otroso1 = (oficina1_otros * oficina1_otros_consumoenergetico) / oficina1_otros
            consumokwh_computadoreso1 = (oficina1_computadores * promedio_consumo_computadoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_monitoreso1 = (oficina1_monitores * promedio_consumo_monitoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_impresoraso1 = (oficina1_impresora * promedio_consumo_impresorao1 * 100 * 8 * 250 / 1000)
            consumokwh_ventiladoreso1 = (oficina1_ventiladores * promedio_consumo_ventiladores1 * 100 * 8 * 250 / 1000)
            consumokwh_airesacondicionadoso1 = (oficina1_airesacondicionados * promedio_consumo_airesacondicionadoso1 * 100 * 8 * 250 / 1000)
            consumokwh_refrigeradoreso1 = (oficina1_refrigeradores * promedio_consumo_refrigeradoreso1 * 100 * 8 * 250 / 1000)
            consumokwh_iluminaciono1 = (oficina1_iluminacion * promedio_consumo_iluminaciono1 * 100 * 8 * 250 / 1000)
            consumokwh_otroso1 = (oficina1_otros * promedio_consumo_otroso1 * 100 * 8 * 250 / 1000)
            emisionestotales_computadoraso1 = (consumokwh_computadoreso1 * factor_emision)
            emisionestotales_monitoreso1 = (consumokwh_monitoreso1 * factor_emision)
            emisionestotales_impresoraso1 = (consumokwh_impresoraso1 * factor_emision)
            emisionestotales_ventiladoreso1 = (consumokwh_ventiladoreso1 * factor_emision)
            emisionestotales_airesacondicionadoso1 = (consumokwh_airesacondicionadoso1 * factor_emision)
            emisionestotales_refrigeradoreso1 = (consumokwh_refrigeradoreso1 * factor_emision)
            emisionestotales_iluminaciono1 = (consumokwh_iluminaciono1 * factor_emision)
            emisionestotales_otroso1 = (consumokwh_otroso1 * factor_emision)
            emisionestotales_ofinina1 = emisionestotales_computadoraso1 + emisionestotales_impresoraso1 + emisionestotales_impresoraso1 + emisionestotales_ventiladoreso1 +    emisionestotales_airesacondicionadoso1 + emisionestotales_refrigeradoreso1 + emision_iluminacion_oficina1 + emisionestotales_otroso1
            print (f'la ofinina 2 genera un total de {emisionestotales_ofinina1} kg de co2 por año por energia de los equipos electricos') 
            x = input ('presione tecla para continuar......')
            
